name: openrgb
description: OpenRGB Dart Client
version: 0.0.1
homepage: https://github.com/Vonarian/OpenRGB

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  color: ^3.0.0
  quiver: ^3.1.0


dev_dependencies:
  flutter_lints: 2.0.1